<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="Zone" Id="{555fce11-eff5-0ccb-1ed8-8a44af541b59}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Zone
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// ]]></ST>
    </Implementation>
    <LineIds Name="Zone">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>